# Site settings
title: A place for thoughts
email: justinwatt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A running log to keep track of all the things I want to learn.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  justinwatt

# Build settings
markdown: kramdown
